name: daily github action
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 0 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      - run: pip install requests
      - run: pip install beautifulsoup4
      - run: python src/hllqk.py
    env:
        PASS: ${{ secrets.PASS }}
        PROXY: ${{ secrets.PROXY }}
